# coding: utf-8

# flake8: noqa

"""
    DEMO API Restful

    API realizzata per presentare una demo di funzionamento RESTful Sistemi paralelli e distributiti (flipped lessons) anno: 2022/2023   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.corsi_body import CorsiBody
from swagger_client.models.corsi_corso_id_body import CorsiCorsoIdBody
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response2001 import InlineResponse2001
from swagger_client.models.inline_response404 import InlineResponse404
