externalDocs:
  description: Maggiori info
  url: https://github.com/HeroS3c-new/Demo-RESTful
info:
  description: 'API realizzata per presentare una demo di funzionamento RESTful

    Sistemi paralelli e distributiti (flipped lessons) anno: 2022/2023 '
  title: DEMO API Restful
  version: 1.0.0
openapi: 3.0.3
paths:
  /corsi:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  properties:
                    dipartimento:
                      description: Dipartimento del corso
                      type: string
                    id:
                      description: ID del corso
                      type: integer
                    nome:
                      description: Nome del corso
                      type: string
                  type: object
                type: array
          description: Elenco dei corsi restituito con successo
      summary: Restituisce tutti i corsi
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                dipartimento:
                  description: Dipartimento del corso
                  type: string
                nome:
                  description: Nome del corso
                  type: string
              type: object
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                properties:
                  dipartimento:
                    description: Dipartimento del corso
                    type: string
                  id:
                    description: ID del corso
                    type: integer
                  nome:
                    description: Nome del corso
                    type: string
                type: object
          description: Corso creato con successo
      summary: Crea un nuovo corso
  /corsi/{corso_id}:
    delete:
      parameters:
      - in: path
        name: corso_id
        required: true
        schema:
          description: ID del corso
          type: integer
      responses:
        '204':
          description: Corso eliminato con successo
        '404':
          content:
            application/json:
              schema:
                properties:
                  messaggio:
                    description: Messaggio di errore
                    type: string
                type: object
          description: Corso non trovato
      summary: Elimina un corso esistente
    get:
      parameters:
      - in: path
        name: corso_id
        required: true
        schema:
          description: ID del corso
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  dipartimento:
                    description: Dipartimento del corso
                    type: string
                  id:
                    description: ID del corso
                    type: integer
                  nome:
                    description: Nome del corso
                    type: string
                type: object
          description: Corso restituito con successo
        '404':
          content:
            application/json:
              schema:
                properties:
                  messaggio:
                    description: Messaggio di errore
                    type: string
                type: object
          description: Corso non trovato
      summary: Restituisce un corso specifico
    put:
      parameters:
      - in: path
        name: corso_id
        required: true
        schema:
          description: ID del corso
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              properties:
                dipartimento:
                  description: Dipartimento del corso
                  type: string
                nome:
                  description: Nome del corso
                  type: string
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  dipartimento:
                    description: Dipartimento del corso.
                    type: string
                  id:
                    description: ID del corso
                    type: integer
                  nome:
                    description: Nome del corso
                    type: string
                type: object
          description: Corso aggiornato con successo
        '404':
          content:
            application/json:
              schema:
                properties:
                  messaggio:
                    description: Messaggio di errore
                    type: string
                type: object
          description: Corso non trovato
      summary: Aggiorna un corso esistente
servers:
- url: http://localhost:5000
