openapi: 3.0.3
info:
  title: DEMO API Restful
  description: |-
   API realizzata per presentare una demo di funzionamento RESTful
   Sistemi paralelli e distributiti (flipped lessons) anno: 2022/2023 
  version: 1.0.0
externalDocs:
  description: Maggiori info
  url: https://github.com/HeroS3c-new/Demo-RESTful
servers:
  - url: https://f411-145-224-104-33.ngrok.io/corsi
paths:
  /corsi:
    get:
      summary: Restituisce tutti i corsi
      responses:
        '200':
          description: Elenco dei corsi restituito con successo
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: ID del corso
                    nome:
                      type: string
                      description: Nome del corso
                    dipartimento:
                      type: string
                      description: Dipartimento del corso
    post:
      summary: Crea un nuovo corso
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome del corso
                dipartimento:
                  type: string
                  description: Dipartimento del corso
      responses:
        '201':
          description: Corso creato con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID del corso
                  nome:
                    type: string
                    description: Nome del corso
                  dipartimento:
                    type: string
                    description: Dipartimento del corso
  /corsi/{corso_id}:
    get:
      summary: Restituisce un corso specifico
      parameters:
        - in: path
          name: corso_id
          required: true
          schema:
            type: integer
            description: ID del corso
      responses:
        '200':
          description: Corso restituito con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID del corso
                  nome:
                    type: string
                    description: Nome del corso
                  dipartimento:
                    type: string
                    description: Dipartimento del corso
        '404':
          description: Corso non trovato
          content:
            application/json:
              schema:
                type: object
                properties:
                  messaggio:
                    type: string
                    description: Messaggio di errore
    put:
      summary: Aggiorna un corso esistente
      parameters:
        - in: path
          name: corso_id
          required: true
          schema:
            type: integer
            description: ID del corso
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome del corso
                dipartimento:
                  type: string
                  description: Dipartimento del corso
      responses:
        '200':
          description: Corso aggiornato con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID del corso
                  nome:
                    type: string
                    description: Nome del corso
                  dipartimento:
                    type: string
                    description: Dipartimento del corso.
        '404':
          description: Corso non trovato
          content:
            application/json:
              schema:
                type: object
                properties:
                  messaggio:
                    type: string
                    description: Messaggio di errore
    delete:
      summary: Elimina un corso esistente
      parameters:
        - in: path
          name: corso_id
          required: true
          schema:
            type: integer
            description: ID del corso
      responses:
        '204':
          description: Corso eliminato con successo
        '404':
          description: Corso non trovato
          content:
            application/json:
              schema:
                type: object
                properties:
                  messaggio:
                    type: string
                    description: Messaggio di errore

                            