# coding: utf-8

"""
    DEMO API Restful

    API realizzata per presentare una demo di funzionamento RESTful Sistemi paralelli e distributiti (flipped lessons) anno: 2022/2023   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.corsi_body import CorsiBody  # noqa: E501
from swagger_client.rest import ApiException


class TestCorsiBody(unittest.TestCase):
    """CorsiBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCorsiBody(self):
        """Test CorsiBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.corsi_body.CorsiBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
