# coding: utf-8

"""
    DEMO API Restful

    API realizzata per presentare una demo di funzionamento RESTful Sistemi paralelli e distributiti (flipped lessons) anno: 2022/2023   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_corsi_corso_id_delete(self):
        """Test case for corsi_corso_id_delete

        Elimina un corso esistente  # noqa: E501
        """
        pass

    def test_corsi_corso_id_get(self):
        """Test case for corsi_corso_id_get

        Restituisce un corso specifico  # noqa: E501
        """
        pass

    def test_corsi_corso_id_put(self):
        """Test case for corsi_corso_id_put

        Aggiorna un corso esistente  # noqa: E501
        """
        pass

    def test_corsi_get(self):
        """Test case for corsi_get

        Restituisce tutti i corsi  # noqa: E501
        """
        pass

    def test_corsi_post(self):
        """Test case for corsi_post

        Crea un nuovo corso  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
